# Generated by Django 4.1.3 on 2022-12-22 03:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.TextField(max_length=100)),
                ('image', models.ImageField(default='default_post_image.avif', upload_to='post_images')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now)),
                ('type', models.TextField(default='Cho thuê')),
                ('location', models.TextField()),
                ('district', models.TextField(default='Undefined District')),
                ('price', models.IntegerField(default=0)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('bio', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('phone_number', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('profileimg', models.ImageField(default='blank-profile-picture.png', upload_to='profile_image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
