# Generated by Django 4.1.3 on 2022-12-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='housetype',
            field=models.TextField(default='Không chung chủ'),
        ),
    ]
