# Generated by Django 4.1.3 on 2023-02-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wishlist_wishlistitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='wishlistitems',
            name='post',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistItems',
        ),
    ]
