# Generated by Django 4.1.3 on 2023-02-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_savepost_post_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='save_check',
            field=models.IntegerField(default=0),
        ),
    ]
