# Generated by Django 4.1.3 on 2023-03-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_save_check'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavePost',
            new_name='LikePost',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='save_check',
            new_name='like_check',
        ),
    ]
