# Generated by Django 4.1.3 on 2023-03-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_savepost_likepost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_check',
            field=models.IntegerField(default=70),
        ),
    ]
