# Generated by Django 4.1.3 on 2023-03-12 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_post_like_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_wishList',
            field=models.ManyToManyField(blank=True, related_name='user_wishList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_check',
            field=models.IntegerField(default=56),
        ),
    ]
